{% set name = "decopatch" %}
{% set version = "1.4.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/decopatch-{{ version }}.tar.gz
  sha256: 957f49c93f4150182c23f8fb51d13bb3213e0f17a79e09c8cca7057598b55720

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools_scm
  run:
    - makefun >=1.5.0
    - python >={{ python_min }}

test:
  imports:
    - decopatch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smarie/python-decopatch
  summary: Create decorators easily in python.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    Because of a tiny oddity in the python language, writing decorators without
    help can be a pain because you have to handle the no-parenthesis usage
    explicitly. `decopatch` provides a simple way to solve this issue so that
    writing decorators is simple and straightforward.
  doc_url: https://smarie.github.io/python-decopatch
  dev_url: https://github.com/smarie/python-decopatch

extra:
  recipe-maintainers:
    - smarie
